-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 01:29:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema colegio_online
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `colegio_online` ;

-- -----------------------------------------------------
-- Schema colegio_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio_online` DEFAULT CHARACTER SET utf8mb4 ;
USE `colegio_online` ;

-- -----------------------------------------------------
-- Table `colegio_online`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`status` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX `id_status_UNIQUE` (`id_status` ASC),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio_online`.`asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`asignaturas` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`asignaturas` (
  `id_asignatura` INT(99) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(99) NOT NULL,
  `nombre` VARCHAR(99) NOT NULL,
  `minimo` DOUBLE NOT NULL,
  `maximo` DOUBLE NOT NULL,
  `status_id_status` INT NOT NULL,
  PRIMARY KEY (`id_asignatura`),
  INDEX `fk_asignaturas_status1_idx` (`status_id_status` ASC),
  UNIQUE INDEX `id_asignatura_UNIQUE` (`id_asignatura` ASC),
  CONSTRAINT `fk_asignaturas_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `colegio_online`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`usuarios` (
  `id_usuario` INT(99) NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(99) NOT NULL,
  `password` VARCHAR(99) NOT NULL,
  `status_id_status` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_status1_idx` (`status_id_status` ASC),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  CONSTRAINT `fk_usuarios_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `colegio_online`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`docentes` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`docentes` (
  `id_docentes` INT(99) NOT NULL AUTO_INCREMENT,
  `nombre1` VARCHAR(99) NOT NULL,
  `nombre2` VARCHAR(99) NOT NULL,
  `apellido1` VARCHAR(99) NOT NULL,
  `apellido2` VARCHAR(99) NOT NULL,
  `cedula` VARCHAR(99) NOT NULL,
  `sexo` VARCHAR(99) NOT NULL,
  `fecha` VARCHAR(99) NOT NULL,
  `nacionalidad` VARCHAR(99) NOT NULL,
  `celular` VARCHAR(99) NOT NULL,
  `telefono` VARCHAR(99) NOT NULL,
  `correo` VARCHAR(99) NOT NULL,
  `direccion` VARCHAR(99) NOT NULL,
  `status_id_status` INT NOT NULL,
  `usuarios_id_usuario` INT(99) NOT NULL,
  PRIMARY KEY (`id_docentes`),
  INDEX `fk_planilla_docente_status1_idx` (`status_id_status` ASC),
  INDEX `fk_docentes_usuarios1_idx` (`usuarios_id_usuario` ASC),
  UNIQUE INDEX `id_docentes_UNIQUE` (`id_docentes` ASC),
  CONSTRAINT `fk_planilla_docente_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `colegio_online`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docentes_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `colegio_online`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`plan_evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`plan_evaluacion` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`plan_evaluacion` (
  `id_plan_evaluacion` INT(99) NOT NULL AUTO_INCREMENT,
  `numero` INT(99) NOT NULL,
  `titulo` VARCHAR(99) NOT NULL,
  `escala` INT(99) NOT NULL,
  `peso` INT(99) NOT NULL,
  `asignaturas_id_asignatura` INT(99) NOT NULL,
  PRIMARY KEY (`id_plan_evaluacion`),
  INDEX `fk_plan_evaluacion_asignaturas1_idx` (`asignaturas_id_asignatura` ASC),
  UNIQUE INDEX `id_plan_evaluacion_UNIQUE` (`id_plan_evaluacion` ASC),
  CONSTRAINT `fk_plan_evaluacion_asignaturas1`
    FOREIGN KEY (`asignaturas_id_asignatura`)
    REFERENCES `colegio_online`.`asignaturas` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`calificacion` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`calificacion` (
  `id_calificacion` INT(99) NOT NULL AUTO_INCREMENT,
  `calificacion` DOUBLE NOT NULL,
  `fecha_carga` VARCHAR(99) NOT NULL,
  `docentes_id_docentes` INT(99) NOT NULL,
  `plan_evaluacion_id_plan_evaluacion` INT(99) NOT NULL,
  PRIMARY KEY (`id_calificacion`),
  INDEX `fk_calificacion_docentes1_idx` (`docentes_id_docentes` ASC),
  INDEX `fk_calificacion_plan_evaluacion1_idx` (`plan_evaluacion_id_plan_evaluacion` ASC),
  UNIQUE INDEX `id_calificacion_UNIQUE` (`id_calificacion` ASC),
  CONSTRAINT `fk_calificacion_docentes1`
    FOREIGN KEY (`docentes_id_docentes`)
    REFERENCES `colegio_online`.`docentes` (`id_docentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_plan_evaluacion1`
    FOREIGN KEY (`plan_evaluacion_id_plan_evaluacion`)
    REFERENCES `colegio_online`.`plan_evaluacion` (`id_plan_evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`docentes_materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`docentes_materias` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`docentes_materias` (
  `id_docentes_materias` INT(99) NOT NULL AUTO_INCREMENT,
  `docentes_id_docentes` INT(99) NOT NULL,
  `asignaturas_id_asignatura` INT(99) NOT NULL,
  PRIMARY KEY (`id_docentes_materias`),
  INDEX `fk_docentes_materias_docentes1_idx` (`docentes_id_docentes` ASC),
  INDEX `fk_docentes_materias_asignaturas1_idx` (`asignaturas_id_asignatura` ASC),
  UNIQUE INDEX `id_docentes_materias_UNIQUE` (`id_docentes_materias` ASC),
  CONSTRAINT `fk_docentes_materias_docentes1`
    FOREIGN KEY (`docentes_id_docentes`)
    REFERENCES `colegio_online`.`docentes` (`id_docentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docentes_materias_asignaturas1`
    FOREIGN KEY (`asignaturas_id_asignatura`)
    REFERENCES `colegio_online`.`asignaturas` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`periodo` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`periodo` (
  `id_periodo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(99) NOT NULL,
  `fecha_inicio` VARCHAR(99) NOT NULL,
  `fecha_fin` VARCHAR(99) NOT NULL,
  `status_id_status` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`id_periodo`),
  INDEX `fk_periodo_status1_idx` (`status_id_status` ASC),
  UNIQUE INDEX `id_periodo_UNIQUE` (`id_periodo` ASC),
  CONSTRAINT `fk_periodo_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `colegio_online`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`estudiantes` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`estudiantes` (
  `id_estudiantes` INT(99) NOT NULL AUTO_INCREMENT,
  `nombre1` VARCHAR(99) NOT NULL,
  `nombre2` VARCHAR(99) NOT NULL,
  `apellido1` VARCHAR(99) NOT NULL,
  `apellido2` VARCHAR(99) NOT NULL,
  `cedula` VARCHAR(99) NOT NULL,
  `sexo` VARCHAR(99) NOT NULL,
  `fecha` VARCHAR(99) NOT NULL,
  `nacionalidad` VARCHAR(99) NOT NULL,
  `celular` VARCHAR(99) NOT NULL,
  `telefono` VARCHAR(99) NOT NULL,
  `correo` VARCHAR(99) NOT NULL,
  `direccion` VARCHAR(99) NOT NULL,
  `procedencia` VARCHAR(99) NOT NULL,
  `anio` VARCHAR(99) NOT NULL,
  `cedula_r` VARCHAR(99) NOT NULL,
  `usuarios_id_usuario` INT(99) NOT NULL,
  `status_id_status` INT NOT NULL,
  PRIMARY KEY (`id_estudiantes`),
  INDEX `fk_estudiantes_usuarios1_idx` (`usuarios_id_usuario` ASC),
  INDEX `fk_estudiantes_status1_idx` (`status_id_status` ASC),
  UNIQUE INDEX `id_estudiantes_UNIQUE` (`id_estudiantes` ASC),
  CONSTRAINT `fk_estudiantes_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `colegio_online`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `colegio_online`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`publicaciones` (
  `id_publicacion` INT(99) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(99) NOT NULL,
  `mensaje` VARCHAR(99) NOT NULL,
  `fecha` VARCHAR(99) NOT NULL,
  `hora` VARCHAR(99) NOT NULL,
  PRIMARY KEY (`id_publicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`secciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`secciones` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`secciones` (
  `id_seccion` INT(99) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(99) NOT NULL,
  `nombre` VARCHAR(99) NOT NULL,
  `status_id_status` INT NOT NULL,
  PRIMARY KEY (`id_seccion`),
  INDEX `fk_secciones_status1_idx` (`status_id_status` ASC),
  UNIQUE INDEX `id_seccion_UNIQUE` (`id_seccion` ASC),
  CONSTRAINT `fk_secciones_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `colegio_online`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio_online`.`paquetes_materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`paquetes_materias` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`paquetes_materias` (
  `id_paquete_materias` INT NOT NULL AUTO_INCREMENT,
  `seccion_id_seccion` INT(99) NOT NULL,
  `asignaturas_id_asignatura` INT(99) NOT NULL,
  PRIMARY KEY (`id_paquete_materias`),
  UNIQUE INDEX `id_paquete_materias_UNIQUE` (`id_paquete_materias` ASC),
  INDEX `fk_paquete_materias_seccion1_idx` (`seccion_id_seccion` ASC),
  INDEX `fk_paquete_materias_asignaturas1_idx` (`asignaturas_id_asignatura` ASC),
  CONSTRAINT `fk_paquete_materias_seccion1`
    FOREIGN KEY (`seccion_id_seccion`)
    REFERENCES `colegio_online`.`secciones` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_materias_asignaturas1`
    FOREIGN KEY (`asignaturas_id_asignatura`)
    REFERENCES `colegio_online`.`asignaturas` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio_online`.`estudiantes_secciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`estudiantes_secciones` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`estudiantes_secciones` (
  `idestudiantes_secciones` INT NOT NULL AUTO_INCREMENT,
  `estudiantes_id_p_e` INT(99) NOT NULL,
  `secciones_id_seccion` INT(99) NOT NULL,
  PRIMARY KEY (`idestudiantes_secciones`),
  UNIQUE INDEX `idestudiantes_secciones_UNIQUE` (`idestudiantes_secciones` ASC),
  INDEX `fk_estudiantes_secciones_estudiantes1_idx` (`estudiantes_id_p_e` ASC),
  INDEX `fk_estudiantes_secciones_secciones1_idx` (`secciones_id_seccion` ASC),
  CONSTRAINT `fk_estudiantes_secciones_estudiantes1`
    FOREIGN KEY (`estudiantes_id_p_e`)
    REFERENCES `colegio_online`.`estudiantes` (`id_estudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_secciones_secciones1`
    FOREIGN KEY (`secciones_id_seccion`)
    REFERENCES `colegio_online`.`secciones` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio_online`.`periodos_secciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`periodos_secciones` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`periodos_secciones` (
  `id_periodos_secciones` INT NOT NULL AUTO_INCREMENT,
  `periodo_id_periodo` INT(11) NOT NULL,
  `secciones_id_seccion` INT(99) NOT NULL,
  PRIMARY KEY (`id_periodos_secciones`),
  UNIQUE INDEX `id_periodos_secciones_UNIQUE` (`id_periodos_secciones` ASC),
  INDEX `fk_periodos_secciones_periodo1_idx` (`periodo_id_periodo` ASC),
  INDEX `fk_periodos_secciones_secciones1_idx` (`secciones_id_seccion` ASC),
  CONSTRAINT `fk_periodos_secciones_periodo1`
    FOREIGN KEY (`periodo_id_periodo`)
    REFERENCES `colegio_online`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodos_secciones_secciones1`
    FOREIGN KEY (`secciones_id_seccion`)
    REFERENCES `colegio_online`.`secciones` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio_online`.`usuarios_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio_online`.`usuarios_roles` ;

CREATE TABLE IF NOT EXISTS `colegio_online`.`usuarios_roles` (
  `id_usuarios_roles` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `usuarios_id_usuario` INT(99) NOT NULL,
  PRIMARY KEY (`id_usuarios_roles`),
  UNIQUE INDEX `id_usuarios_roles_UNIQUE` (`id_usuarios_roles` ASC),
  INDEX `fk_usuarios_roles_usuarios1_idx` (`usuarios_id_usuario` ASC),
  CONSTRAINT `fk_usuarios_roles_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `colegio_online`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
